// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL2gjFrSHyj2vr4bVqSaGj1SQ8OCj894A',
    appId: '1:695130933272:web:97076ade3cac9b082a9b6d',
    messagingSenderId: '695130933272',
    projectId: 'learning-minimal-chat-app',
    authDomain: 'learning-minimal-chat-app.firebaseapp.com',
    storageBucket: 'learning-minimal-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs2GZiUTZb8xbmKBrJ_ZOVzEhh1ss7uxw',
    appId: '1:695130933272:android:ebb777f4f31616772a9b6d',
    messagingSenderId: '695130933272',
    projectId: 'learning-minimal-chat-app',
    storageBucket: 'learning-minimal-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVYJgzZJFIb7KGIN6ycxtVKqsB6V9ODS0',
    appId: '1:695130933272:ios:624a99eccd19cbde2a9b6d',
    messagingSenderId: '695130933272',
    projectId: 'learning-minimal-chat-app',
    storageBucket: 'learning-minimal-chat-app.appspot.com',
    iosBundleId: 'com.example.learningMinimalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVYJgzZJFIb7KGIN6ycxtVKqsB6V9ODS0',
    appId: '1:695130933272:ios:624a99eccd19cbde2a9b6d',
    messagingSenderId: '695130933272',
    projectId: 'learning-minimal-chat-app',
    storageBucket: 'learning-minimal-chat-app.appspot.com',
    iosBundleId: 'com.example.learningMinimalChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL2gjFrSHyj2vr4bVqSaGj1SQ8OCj894A',
    appId: '1:695130933272:web:d29017959aac2c1e2a9b6d',
    messagingSenderId: '695130933272',
    projectId: 'learning-minimal-chat-app',
    authDomain: 'learning-minimal-chat-app.firebaseapp.com',
    storageBucket: 'learning-minimal-chat-app.appspot.com',
  );
}
